#!/usr/bin/env ruby

# :set filetype=rb

# Set up gems listed in the Gemfile.
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __FILE__)

require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])

require_relative 'lib/reviewer'

if ARGV.empty?
  puts "Usage: review 'user/repo'"
  exit
end

githubRepo = ARGV[0]
reviewer = Reviewer.new(githubRepo)
reviewer.review_pull_requests
reviewer.review_results





